/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import com.controller.GetListCustomer;
import com.model.Customer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin-pc
 */
public class CustomerManageInformation extends javax.swing.JFrame implements  ActionListener{
    ArrayList<Customer> list;
    /**
     * Creates new form CustomerManage
     */
    public CustomerManageInformation() {
        initComponents();
        setLocationRelativeTo(null);
        btnAddCustomer.addActionListener(this);
        btnUpdateCustomer.addActionListener(this);
        btnDeleteCustomer.addActionListener(this);
        btnDisplayDatabase.addActionListener(this);
        btnBack.addActionListener(this);
        list = GetListCustomer.getListCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerManage = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDisplayDatabase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CustomerManage");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 204));

        customerManage.setBackground(new java.awt.Color(102, 0, 255));
        customerManage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerManage.setForeground(new java.awt.Color(102, 102, 0));
        customerManage.setText("QUẢN LÝ KHÁCH HÀNG");

        btnAddCustomer.setBackground(new java.awt.Color(0, 204, 204));
        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(51, 51, 51));
        btnAddCustomer.setText("Thêm Khách Hàng");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnUpdateCustomer.setBackground(new java.awt.Color(0, 204, 204));
        btnUpdateCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateCustomer.setText("Sửa Thông Tin Khách Hàng");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setBackground(new java.awt.Color(0, 204, 204));
        btnDeleteCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteCustomer.setText("Xóa Thông Tin Khách Hàng");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setText("Trở Về");

        btnDisplayDatabase.setBackground(new java.awt.Color(204, 204, 0));
        btnDisplayDatabase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDisplayDatabase.setText("Hiển Thị Danh Sách Khách Hàng");
        btnDisplayDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayDatabaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(customerManage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDisplayDatabase)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerManage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDisplayDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnDisplayDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisplayDatabaseActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerManageInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerManageInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerManageInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerManageInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerManageInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnDisplayDatabase;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JLabel customerManage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnAddCustomer)) addInforCustomer();
        else if(e.getSource().equals(btnUpdateCustomer)) updateInforCustomer();
        else if(e.getSource().equals(btnDeleteCustomer)) deleteInforCustomer();
        else if(e.getSource().equals(btnDisplayDatabase)) displayDatabase();
        else back();
    }
    
    public void addInforCustomer(){
        new AddCustomerInformation().setVisible(true);
        this.dispose();
    }
    
    public void updateInforCustomer(){
        if(list.size()==0){
            JOptionPane.showMessageDialog(rootPane, "Database empty !!! Make a new database, please ...");
        } else {
            new UpdateCustomerInformation().setVisible(true);
            this.dispose();
        }
    }
    
    public void deleteInforCustomer(){
        if(list.size()==0){
            JOptionPane.showMessageDialog(rootPane, "Database empty !!! Make a new database, please ...");
        } else {
            new DeleteCustomerInformation().setVisible(true);
            this.dispose();
        }
    }
    
    public void back(){
        new MainManagePage().setVisible(true);
        this.dispose();
    }
    
    public void displayDatabase(){
        if(list.size()==0){
            JOptionPane.showMessageDialog(rootPane, "Database empty !!!");
        } else {
            new DisplayDatabaseCustomer().setVisible(true);
            this.dispose();
        }
    }
}
